# Generated by Django 4.0.1 on 2022-02-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('actividad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombregrupo', models.CharField(max_length=40)),
                ('actividad', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='NotaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('actividad', models.CharField(max_length=40)),
                ('nota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NotaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombregrupo', models.CharField(max_length=40)),
                ('actividad', models.CharField(max_length=40)),
                ('nota', models.IntegerField()),
            ],
        ),
    ]
